{% set name = "genson" %}
{% set version = "1.3.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "e02db9ac2e3fd29e65b5286f7135762e2cd8a986537c075b06fc5f1517308e37" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  entry_points:
    - genson = genson.__main__:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=44

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - genson

  commands:
    - genson --help

about:
  home: https://github.com/wolverdude/genson/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: GenSON is a powerful, user-friendly JSON Schema generator.
  dev_url: https://github.com/wolverdude/genson/

extra:
  recipe-maintainers:
    - pmlandwehr
    - fhoehle
