{% set name = "genson" %}
{% set version = "1.2.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "40b8faa17f53240f224d683d7a302b5f7b35eb7ab2aba1c223a58a38b8d09c42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  entry_points:
    - genson = genson.cli:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - genson

  commands:
    - genson --help

about:
  home: https://github.com/wolverdude/genson/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: GenSON is a powerful, user-friendly JSON Schema generator.
  dev_url: https://github.com/wolverdude/genson/

extra:
  recipe-maintainers:
    - pmlandwehr
