travis:
  secure:
    BINSTAR_TOKEN: YDECjlB8BdHinebD4bBY+qaTItT7FhADyvR/iOFS+h1YSvmdFxxUh56UHS4/iU97GBw/u9ZHFJQeXzFDQfw+6Bs2Q/HSXL9fAx3MymCBfAP9k+gEC05pPfVr1YKOmegWBR4cwkMcQCTbJPdbn8Wh5DXduIeEkE0FfA/A9Gw67aGnAxT9yOEsxR6iw5+7SrZFLkEkbEvgM7UMCN6llLKkQtEs+X5K0XLwklAZRzhj6a1yVfmadx9rWUtdRx2aVBrCPiS3h/KiNSb+dC2Nix5OPO/D/nn2FpdYg+3N9VIMRkUwf75hZHKst28vfsflldvlQzV1ZOfQ7jUfLwtOzVHJwIHPSwYXcSnOSHY5Kh+xWccX9ecughG/w1JYx9j0z8+YAXprwUOCPyj3KO2UOoX4wBiCMZKCq8qj3ZICnCVPJrSX5/cx2JtUL8SOoPBZt1iJJ7C4fPAG5pc4HMRT+iGfXyHTCQvCz/glyNnaICxthD7CrwXC4A5A6KgmANCQaOmK0mifvloEENNxmmmdvezMU9UOyGtzkvPtWeWQvpECzLd6ootJUc3TpTtFlIkAjkJdWC7bTnbfUUyPiUtrf/tG8dwWjKtzFI1Aap/2Qo9twrPP+YCGpoekzT7dcv8joVe9LNCiqNyTWXb5pdWVpgJ6xO2GXZrbBEZMO1gqVoQPc2g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
